FROM python:3.11-slim

WORKDIR /app

COPY ./api/requirements.txt .
COPY ./rag_core/torch-2.9.1+cpu-cp311-cp311-manylinux_2_28_x86_64.whl .

RUN pip install --no-cache-dir torch-2.9.1+cpu-cp311-cp311-manylinux_2_28_x86_64.whl

# Use a cache mount to speed up pip install on subsequent builds
RUN --mount=type=cache,target=/root/.cache/pip pip install --retries 5 --default-timeout=1000 -r requirements.txt

COPY ./api/app /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

